version: "3.5"

services:
  node:
      build:
        context: .
        dockerfile: Dockerfile-node
      networks:
        - conet

  web:
      build:
        context: .
        dockerfile: Dockerfile-nginx
      ports:
        - 8000:80
        - 4430:443
      expose:
        - 443
        - 80
      networks:
        - conet

networks:
  conet:
    external: false
