version: "3.5"

services:
  node:
      image: tzone85/cloudone-api:node
      networks:
        - conet
      environment:


  web:
      image: tzone85/cloudone-api:nginx
      ports:
        - 80:80
        - 4430:443
      expose:
        - 443
        - 80
      networks:
        - conet

networks:
  conet:
    external: false
